# Generated by Django 3.0 on 2020-01-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nombre',
            new_name='tratamiento',
        ),
    ]
